citas_app/urls.py
from django.urls import path
from . import views
from .views import *

#namespace para acceder a las urls de la aplicacion 'citas_app'
app_name = 'citas_app'

urlpatterns = [
    path('user_registration/', UserRegisterView.as_view(), name='user_registration_view'), 
    path('full_user_registration/', CompletePatientRecordView.as_view(), name='full_patient_registration_view'), 
    path('appointments_index/', appointments_index, name='appointments_index'),    
    path('patients_index/',patients_index, name='patients_index'),
    path('contact_index/',contact_index, name='contact_index'), 
    path('appointments_list/', CitaMedicaListView.as_view(), name='appointments_list'),
    path('closest_appointments/', closest_appointments, name='closest_appointments'),
    path('appointments_create/', CitaMedicaCreateView, name='appointments_create'),
    path('appointments_update/<int:pk>/', CitaMedicaUpdateView.as_view(), name='appointments_update'),
    path('appointments_delete/<int:pk>/', CitaMedicaDeleteView.as_view(), name='appointments_delete'),  
    path('doctors_index/',doctors_index, name='doctors_index'),
    path('doctors_list/', MedicoListView, name='doctors_list'),
    path('doctors_create/', views.MedicoCreateView, name='doctors_create'),
    path('vista_solicitudes_medico/', vista_solicitudes_medico, name='vista_solicitudes_medico'),
    path('doctors_update/<int:pk>/', MedicoUpdateView, name='doctors_update'),
    path('doctors_delete/<int:pk>/', MedicoDeleteView, name='doctors_delete'),
    path('appointments_index_profile_edit/', EditarPerfilPacienteView.as_view(), name='appointments_index_profile_edit'),  
    path('citas_confirmadas_calendar/', CitasConfirmadasCalendar.as_view(), name='citas_confirmadas_calendar'),
    path('confirmar_cita_medico/<int:cita_id>/', confirmar_cita_medico, name='confirmar_cita_medico'),
    path('obtener_eventos/', obtener_eventos, name='obtener_eventos'),
    path('completar_cita/<int:cita_id>/', views.completar_cita, name='completar_cita'),
    path('ver_historial/<int:cita_id>/', ver_historial, name='ver_historial'),
    path('ver_historial_completo/<int:paciente_id>/',ver_historial_completo, name='ver_historial_completo'),
    path('reprogramar-cita/<int:cita_id>/', views.reprogramar_cita, name='reprogramar_cita'),
    path('historial_completo_paciente/', historial_completo_paciente, name='historial_completo_paciente'),
    path('specialties_index/', EspecialidadesView, name='specialties_index'),
    path('citas_generales/', citas_generales, name='citas_generales'),
    path('ver_historial_personal/<int:cita_id>/', ver_historial_personal, name='ver_historial_personal'),
    ]

citas_medicas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from citas_app import views

app_name = 'citas_app' 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.custom_logout_view, name='logout'),
    path('no_login_view/', views.no_login_view, name='no_login_view'), 
    path('medical_appointments/', include('citas_app.urls', namespace='medical_appointments')),
]

      

citas_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Medico, CitaMedica, Paciente, CompletarHistorial

#formualio a renderizar del modelo CitaMedica
class CitaMedicaForm(forms.ModelForm):
    class Meta:
        #modelo a utilizar
        model = CitaMedica
        #se excluye el campo paciente para que no sea visible en el formulario
        exclude = ['paciente']

#formulario a renderizar de la clase UserCreationForm para registrar un usuario
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        #modelo a utilizar
        model = User
        #campos a mostrar
        fields = ['username', 'password1', 'password2']
    #se personalizan los campos
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Usuario'
        self.fields['password1'].label = 'Contraseña'
        self.fields['password2'].label = 'Confirmar'

#formulario a renderizar del modelo MedicoForm
class MedicoForm(forms.ModelForm):
    class Meta:
        #modelo a utilizar
        model = Medico
        #campos a mostrar
        fields = ['nombre_medico', 'apellido_medico', 'especialidad_medico']

    #se personalizan los campos   
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nombre_medico'].label = 'Nombre'
        self.fields['apellido_medico'].label = 'Apellido'
        self.fields['especialidad_medico'].label = 'Especialidad'

    #se vincula el formulario de creacion de usuario para que se muestre junto con
    #el formulario actual
    usuario_medico = CustomUserCreationForm()

#formulario a renderizar del modelo PacienteForm    
class PacienteForm(forms.ModelForm):
    class Meta:
        #modelo a utilizar
        model = Paciente
        #campos a mostrar
        fields = ['nombre_paciente', 'apellido_paciente', 'edad_paciente', 'sexo_paciente', 'fecha_nac_paciente']

#formualio a renderizar basado en ModelForm
class CompletarHistorialForm(forms.ModelForm):
    #se define el campo 'completada' como campo booleano requerido
    completada = forms.BooleanField(
        required=True, 
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),  
    )

    class Meta:
        model = CompletarHistorial
        fields = ['diagnostico', 'tratamiento', 'completada']
        
#formulario a renderizar del modelo ReprogramarCitaForm
class ReprogramarCitaForm(forms.ModelForm):
    class Meta:
        #modelo a utilizar
        model = CitaMedica
        #excluyendo campos para no mostrarlos en el formulario
        exclude = ['paciente','medico']

citas_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy,reverse
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Paciente, Medico, CitaMedica, CompletarHistorial
from .forms import CitaMedicaForm, PacienteForm, MedicoForm, CitaMedicaForm, CustomUserCreationForm, CompletarHistorialForm, ReprogramarCitaForm
from schedule.models import Calendar, Event
from datetime import datetime, timedelta
from .decorators import permiso_medico

#vista encargada del registro inicial de usuario
class UserRegisterView(CreateView):        
    #template a renderizar 
    template_name = 'user_patient_register/user_register.html'
    
    #formulario base
    form_class = UserCreationForm
    
    #metodo de validacion de formulario e inicio de sesion
    def form_valid(self, form):        
        #respuesta al estar validado el formulario
        response = super().form_valid(form)
        
        #encriptando contraseña de usuario para almacenarla en la base de datos
        self.object.set_password(form.cleaned_data['password1'])
        
        #guardando objeto
        self.object.save()
        
        #iniciando sesion de forma automatica
        login(self.request, self.object)
        
        #devolviendo la respuesta
        return response
    
    #metodo para redireccionar la vista al ser validado el formulario
    def get_success_url(self):
        return reverse_lazy('citas_app:full_patient_registration_view')
    
    
#vista encargada de continuar el registro completo del paciente
@method_decorator(login_required, name='dispatch')
class CompletePatientRecordView(CreateView):    
    #template a renderizar
    template_name = 'user_patient_register/full_patient_registration.html'    
    
    #modelo base para renderizar el formulario
    model = Paciente    
    
    #campos a mostrar en el template
    fields = [
        'nombre_paciente',
        'apellido_paciente',
        'edad_paciente',
        'sexo_paciente',
        'fecha_nac_paciente',
    ]    
    
    #redireccion despues de validar el formulario
    success_url = reverse_lazy('citas_app:appointments_index')
    
    #metodo para validar el formulario y enviar informacion
    def form_valid(self, form):        
        #asociando el usuario de la sesion actual al campo usuario_paciente del formulario
        form.instance.usuario_paciente = self.request.user        
        
        #enviando informacion 
        return super().form_valid(form)

    
#vista encargada de editar el perfil del paciente
class EditarPerfilPacienteView(UpdateView):
    #modelo a utilizar
    model = Paciente
    
    #formualario a utilizar
    form_class = PacienteForm
    
    #template a renderizar
    template_name = 'user_patient_register/full_patient_registration_edit.html'
    
    #vista a redireccionar despues de editar con exito
    success_url = reverse_lazy('citas_app:appointments_index')

    #recuperando el perfil del paciente actual
    def get_object(self):
        return Paciente.objects.get(usuario_paciente=self.request.user)
    
#vista encargada de usuario no autenticado    
def no_login_view(request):
    
    context = {
        'mensaje': 'Gracias por visitarnos, inicia sesion para gestionar tus citas'
    }
    return render(request,'no_login.html', context)


#vista encargada de cerrar sesion de usuario
def custom_logout_view(request):
    logout(request)
    return redirect(reverse_lazy('login'))


#vista principal de medicos
@permiso_medico#permiso de autorizacion para medicos
def doctors_index(request):
    context = {
        'mensaje': 'Gestión de medicos'
    }
    return render(request,'doctors/doctors_index.html', context)


#vista principal de pacientes
@permiso_medico
def patients_index(request):
    pacientes = Paciente.objects.all()
    context = {
        'pacientes': pacientes,
        'mensaje': 'Gestión de pacientes'
    }
    return render(request, 'patients/patients_index.html', context)

#vista principal citas
@login_required
def appointments_index(request):
    user = request.user
    
    # inicializa las variables medico y paciente en None
    medico = None
    paciente = None

    # verifica si el usuario es un médico y obtiene el objeto de médico
    if hasattr(user, 'medico'):
        medico = user.medico
    
    # verifica si el usuario es un paciente y obtiene el objeto de paciente
    if hasattr(user, 'paciente'):
        paciente = user.paciente

    context = {
        'user': user,
        'medico': medico,
        'paciente': paciente,
    }
    return render(request, 'base.html', context)


#vista principal de contacto
@login_required
def contact_index(request):
    context = {
        'mensaje': 'Gestión de contacto'
    }
    return render(request,'contact/contact_index.html', context)

#vista encargada de crear la cita medica
def CitaMedicaCreateView(request):
    #se verifica que el usuario esté autenticado y sea un paciente
    if not request.user.is_authenticated or not hasattr(request.user, 'paciente'):
        return render(request, 'no_login.html', {'message': 'No tienes permiso para crear citas.'})
    
    #obteniendo los dias disponibles para mostrarse en el template de la vista actual
    dias_disponibles = obtener_dias_disponibles()
    
    #validacion del formulario
    if request.method == 'POST':
        form = CitaMedicaForm(request.POST)
        if form.is_valid():
            #se verifica si ya existe una cita para la fecha seleccionada
            fecha = form.cleaned_data['fecha']
            medico = form.cleaned_data['medico']

            #se comprueba si existe una cita con la misma fecha y se muestra un error en caso de ser asi
            if CitaMedica.objects.filter(fecha=fecha, medico=medico).exists():
                
                return render(request, 'CRUD_appointments/error.html', {'form': form, 'error_message': 'No hay mas espacios para esa fecha'})

            #se crea una instancia de CitaMedica pendiente de guardar
            cita_medica = form.save(commit=False)

            #se asigna el paciente (usuario de la sesión) a la cita medica
            cita_medica.paciente = request.user.paciente

            #se guarda la cita médica con el paciente asignado
            cita_medica.save()

            #se redirecciona a la vista asiganda en caso se der almacenada correctamente
            return redirect(reverse_lazy('medical_appointments:appointments_list'))
    
    #caso contrario se renderiza el formulario de nuevo
    else:
        form = CitaMedicaForm()

    #se rederiza el template pasandole el diccionario
    return render(request, 'CRUD_appointments/citas_medicas_create.html', {'form': form, 'dias_disponibles':dias_disponibles})


#vista encargada de mostrar la lista de citas del paciente
@method_decorator(login_required, name='dispatch')
class CitaMedicaListView(ListView):
    #modelo a utilizar
    model = CitaMedica
    
    #template a utilizar
    template_name = 'CRUD_appointments/citas_medicas_list.html'
    
    #nombre de referencia para acceder a los objetos 
    context_object_name = 'solicitudes_citas'

    #se filtran las citas medicas del paciente actualmente autenticado
    def get_queryset(self):
        return CitaMedica.objects.filter(paciente=self.request.user.paciente)
    
    #metodo para pasarle al contexto los dias disponibles del metodo obtener_dias_disponibles()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dias_disponibles'] = obtener_dias_disponibles()        
        return context

#vista encargada de actualizar la cita por parte del paciente
@method_decorator(login_required, name='dispatch') 
class CitaMedicaUpdateView(UpdateView):
    #modelos a utilizar
    model = CitaMedica
    
    #formulario a utilizar
    form_class = CitaMedicaForm
    
    #template a renderizar
    template_name = 'CRUD_appointments/citas_medicas_create.html'
    
    #nombre de referencia para acceder a los objetos 
    context_object_name = 'cita'
    
    #vista a redireccionar despues de editar con exito
    success_url = reverse_lazy('citas_app:appointments_list')
    
    #metodo para pasarle al contexto los dias disponibles del metodo obtener_dias_disponibles()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        context['dias_disponibles'] = obtener_dias_disponibles()        
        return context
    

#vista encargada de eliminar una cita medica por parte del paciente
@method_decorator(login_required, name='dispatch') 
class CitaMedicaDeleteView(DeleteView):
    model = CitaMedica
    template_name = 'CRUD_appointments/citas_medicas_delete_confirm.html'
    context_object_name = 'cita'
    success_url = reverse_lazy('citas_app:appointments_list')
    
#metodo encargado de obtener las citas mas cercanas
def closest_appointments(request):
    #se obtiene la fecha y hora actual
    now = timezone.now()

    #se busca la cita medica mas cercana y confirmada
    proxima_cita = CitaMedica.objects.filter(
        paciente=request.user.paciente, #se filtra por el paciente actual
        fecha__gte=now,  #que la fecha sea mayor o igual a la actual
        confirmado=True, #que la cita este confirmada
        completada=False #que la cita aun no se encuentre completada
    ).order_by('fecha').first()#se ordenan las citas filtradas por fecha
    
    #se busca la cita medica mas cercana y solicitada

citas_app/templates/patients/historial_completo_paciente.html
{% extends "CRUD_appointments/closest_appointments.html" %}

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}
    <div class="container my-5">
        <div class="jumbotron">
            <h3 class="display-6 text-center p-3 text-secondary">Mi Historial General</h3>
            <ul class="list-unstyled">
                {% for registro in historial %}
                    <li>
                        <div class="card col-md-10 offset-1 mb-3 p-3">
                            <div class="card-body">
                                <h3 class="card-title bg-light p-3" style="border-radius: 10px;">Cita del {{ registro.cita_medica.fecha }}</h3>
                                <p class="card-text"><strong>Medico: </strong> {{ registro.cita_medica.medico.nombre_medico }} {{ registro.cita_medica.medico.apellido_medico }}</p>
                                <hr>
                                <p class="card-text"><strong>Tratamiento: </strong> {{ registro.tratamiento }}</p>
                                <p class="card-text"><strong>Diagnóstico: </strong>{{ registro.diagnostico }}</p>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock seccion_principal_02 %}
<!-- fin_seccion_principal_02 -->

citas_app/templates/patients/patients_index.html
{% extends "doctors/doctors_index.html" %}

{% load static %}

<!-- inicio_titulo -->
{% block title %}
    <title>Médicos - MedApp</title>
{% endblock title %}
<!-- fin_titulo -->

<!-- inicio_bloque_CRUD_citas -->
{% block bloque_CRUD_citas %}
    <div class="container">
        <h5 class="text-center">Lista de Citas de Pacientes</h5>
        <input type="text" id="searchInput" placeholder="Buscar paciente..." class="form-control mb-2">
        <div class="table-responsive">
            <table class="table table-striped" id="pacientesTable">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">ID</th>
                        <th class="text-center" scope="col">Usuario</th>
                        <th class="text-center" scope="col">Nombre</th>
                        <th class="text-center" scope="col">Apellidos</th>
                        <th class="text-center" scope="col">Edad</th>
                        <th class="text-center" scope="col">Sexo</th>
                        <th class="text-center" scope="col">Fecha de Nacimiento</th>
                        <th class="text-center" scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for paciente in pacientes %}
                        <tr class="pacienteRow">
                            <td class="text-center">{{ paciente.id }}</td>
                            <td class="text-center">{{ paciente.usuario_paciente }}</td>
                            <td class="text-center">{{ paciente.nombre_paciente }}</td>
                            <td class="text-center">{{ paciente.apellido_paciente }}</td>
                            <td class="text-center">{{ paciente.edad_paciente }}</td>
                            <td class="text-center">{{ paciente.sexo_paciente }}</td>
                            <td class="text-center">{{ paciente.fecha_nac_paciente }}</td>
                            <td class="text-center">
                                <a href="{% url 'citas_app:ver_historial_completo' paciente.id %}" class="btn btn-sm btn-info">Historial completo</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
    <script>
        // Obtén el campo de entrada y la tabla
        const input = document.getElementById("searchInput");
        const table = document.getElementById("pacientesTable");

        // Agrega un evento de escucha para el campo de entrada
        input.addEventListener("keyup", function () {
            const filtro = input.value.toLowerCase();
            const filas = table.querySelectorAll(".pacienteRow");

            filas.forEach(function (fila) {
                const datosFila = fila.querySelectorAll("td");
                let mostrar = false;

                datosFila.forEach(function (celda) {
                    if (celda.textContent.toLowerCase().indexOf(filtro) > -1) {
                        mostrar = true;
                    }
                });

                if (mostrar) {
                    fila.style.display = "";
                } else {
                    fila.style.display = "none";
                }
            });
        });
    </script>
{% endblock bloque_CRUD_citas %}
<!-- fin_bloque_CRUD_citas -->