citas_app/urls.py
from django.urls import path
from . import views
from .views import *

#namespace para acceder a las urls de la aplicacion 'citas_app'
app_name = 'citas_app'

urlpatterns = [
    path('user_registration/', UserRegisterView.as_view(), name='user_registration_view'), 
    path('full_user_registration/', CompletePatientRecordView.as_view(), name='full_patient_registration_view'), 
    path('appointments_index/', appointments_index, name='appointments_index'),    
    path('patients_index/',patients_index, name='patients_index'),
    path('contact_index/',contact_index, name='contact_index'), 
    path('appointments_list/', CitaMedicaListView.as_view(), name='appointments_list'),
    path('closest_appointments/', closest_appointments, name='closest_appointments'),
    path('appointments_create/', CitaMedicaCreateView, name='appointments_create'),
    path('appointments_update/<int:pk>/', CitaMedicaUpdateView.as_view(), name='appointments_update'),
    path('appointments_delete/<int:pk>/', CitaMedicaDeleteView.as_view(), name='appointments_delete'),  
    path('doctors_index/',doctors_index, name='doctors_index'),
    path('doctors_list/', MedicoListView, name='doctors_list'),
    path('doctors_create/', views.MedicoCreateView, name='doctors_create'),
    path('vista_solicitudes_medico/', vista_solicitudes_medico, name='vista_solicitudes_medico'),
    path('doctors_update/<int:pk>/', MedicoUpdateView, name='doctors_update'),
    path('doctors_delete/<int:pk>/', MedicoDeleteView, name='doctors_delete'),
    path('appointments_index_profile_edit/', EditarPerfilPacienteView.as_view(), name='appointments_index_profile_edit'),  
    path('citas_confirmadas_calendar/', CitasConfirmadasCalendar.as_view(), name='citas_confirmadas_calendar'),
    path('confirmar_cita_medico/<int:cita_id>/', confirmar_cita_medico, name='confirmar_cita_medico'),
    path('obtener_eventos/', obtener_eventos, name='obtener_eventos'),
    path('completar_cita/<int:cita_id>/', views.completar_cita, name='completar_cita'),
    path('ver_historial/<int:cita_id>/', ver_historial, name='ver_historial'),
    path('ver_historial_completo/<int:paciente_id>/',ver_historial_completo, name='ver_historial_completo'),
    path('reprogramar-cita/<int:cita_id>/', views.reprogramar_cita, name='reprogramar_cita'),
    path('historial_completo_paciente/', historial_completo_paciente, name='historial_completo_paciente'),
    path('specialties_index/', EspecialidadesView, name='specialties_index'),
    path('citas_generales/', citas_generales, name='citas_generales'),
    path('ver_historial_personal/<int:cita_id>/', ver_historial_personal, name='ver_historial_personal'),
    ]

citas_medicas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from citas_app import views

app_name = 'citas_app' 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.custom_logout_view, name='logout'),
    path('no_login_view/', views.no_login_view, name='no_login_view'), 
    path('medical_appointments/', include('citas_app.urls', namespace='medical_appointments')),
]

      

citas_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Paciente(models.Model):
    
    """
    Modelo de paciente.
    Atributos:
    - usuario_paciente: Usuario para que el paciente agente su cita
    - nombre_paciente: Nombre del paciente.
    - apellido_paciente: Apellido del paciente.
    - edad_paciente: Edad del paciente.
    - sexo_paciente: Sexo del paciente.
    - fecha_nac_paciente: Fecha de nacimiento del paciente.
    """
    
    usuario_paciente = models.OneToOneField(User, on_delete=models.CASCADE, default=None )
    nombre_paciente = models.CharField(max_length=100, null=True)
    apellido_paciente = models.CharField(max_length=100)
    edad_paciente = models.PositiveIntegerField(default=0)
    sexo_paciente = models.CharField(max_length=10, null=True)
    fecha_nac_paciente = models.DateField(default=None)
    
    def __str__(self):
        return f"{self.nombre_paciente} {self.apellido_paciente}"
    
class Medico(models.Model):
    """
    Modelo de médico.
    Atributos:
    - nombre_medico: Nombre del médico.
    - apellido_medico: Apellido del médico.
    - especialidad_medico: Especialidad del médico.
    - usuario_medico: Usuario del médico para poder consultar las citas.
        
    """
    nombre_medico = models.CharField(max_length=100)
    apellido_medico = models.CharField(max_length=100)
    especialidad_medico = models.CharField(max_length=100)
    usuario_medico = models.OneToOneField(User, on_delete=models.CASCADE, related_name='medico')
        
    def __str__(self):
        return f"{self.nombre_medico}{self.apellido_medico}"
    
    
class CitaMedica(models.Model):
    """
    Modelo de cita médica.
    Atributos:
    - paciente: Paciente que tiene la cita.
    - medico: Médico que atiende la cita.
    - fecha: Fecha de la cita.
    - hora: Hora de la cita.
    - motivo: Motivo de la cita.
"""
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
    fecha = models.DateField(default='2023-01-01')
    hora = models.TimeField(default='00:00')
    motivo = models.CharField(max_length=200)
    confirmado = models.BooleanField(default=False)
    completada = models.BooleanField(default=False)   
    def __str__(self):
        return f'Cita Médica #{self.id} - Paciente: {self.paciente.nombre_paciente}, Médico: {self.medico.nombre_medico}'



class CompletarHistorial(models.Model):
    """
    Modelo que representa el historial médico completo de una cita médica.
    Atributos:
    - cita_medica: La cita médica a la que se relaciona este historial.
    - paciente: El paciente relacionado con este historial.
    - fecha: La fecha de creación del historial (se autocompleta).
    - diagnostico: El diagnóstico del paciente para la cita médica.
    - tratamiento: El tratamiento recomendado para el paciente.
    """
    cita_medica = models.ForeignKey(CitaMedica, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now=True)
    diagnostico = models.TextField()
    tratamiento = models.TextField()
    
    def __str__(self):
        return f"{self.cita_medica}"

citas_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy,reverse
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Paciente, Medico, CitaMedica, CompletarHistorial
from .forms import CitaMedicaForm, PacienteForm, MedicoForm, CitaMedicaForm, CustomUserCreationForm, CompletarHistorialForm, ReprogramarCitaForm
from schedule.models import Calendar, Event
from datetime import datetime, timedelta
from .decorators import permiso_medico

#vista encargada del registro inicial de usuario
class UserRegisterView(CreateView):        
    #template a renderizar 
    template_name = 'user_patient_register/user_register.html'
    
    #formulario base
    form_class = UserCreationForm
    
    #metodo de validacion de formulario e inicio de sesion
    def form_valid(self, form):        
        #respuesta al estar validado el formulario
        response = super().form_valid(form)
        
        #encriptando contraseña de usuario para almacenarla en la base de datos
        self.object.set_password(form.cleaned_data['password1'])
        
        #guardando objeto
        self.object.save()
        
        #iniciando sesion de forma automatica
        login(self.request, self.object)
        
        #devolviendo la respuesta
        return response
    
    #metodo para redireccionar la vista al ser validado el formulario
    def get_success_url(self):
        return reverse_lazy('citas_app:full_patient_registration_view')
    
    
#vista encargada de continuar el registro completo del paciente
@method_decorator(login_required, name='dispatch')
class CompletePatientRecordView(CreateView):    
    #template a renderizar
    template_name = 'user_patient_register/full_patient_registration.html'    
    
    #modelo base para renderizar el formulario
    model = Paciente    
    
    #campos a mostrar en el template
    fields = [
        'nombre_paciente',
        'apellido_paciente',
        'edad_paciente',
        'sexo_paciente',
        'fecha_nac_paciente',
    ]    
    
    #redireccion despues de validar el formulario
    success_url = reverse_lazy('citas_app:appointments_index')
    
    #metodo para validar el formulario y enviar informacion
    def form_valid(self, form):        
        #asociando el usuario de la sesion actual al campo usuario_paciente del formulario
        form.instance.usuario_paciente = self.request.user        
        
        #enviando informacion 
        return super().form_valid(form)

    
#vista encargada de editar el perfil del paciente
class EditarPerfilPacienteView(UpdateView):
    #modelo a utilizar
    model = Paciente
    
    #formualario a utilizar
    form_class = PacienteForm
    
    #template a renderizar
    template_name = 'user_patient_register/full_patient_registration_edit.html'
    
    #vista a redireccionar despues de editar con exito
    success_url = reverse_lazy('citas_app:appointments_index')

    #recuperando el perfil del paciente actual
    def get_object(self):
        return Paciente.objects.get(usuario_paciente=self.request.user)
    
#vista encargada de usuario no autenticado    
def no_login_view(request):
    
    context = {
        'mensaje': 'Gracias por visitarnos, inicia sesion para gestionar tus citas'
    }
    return render(request,'no_login.html', context)


#vista encargada de cerrar sesion de usuario
def custom_logout_view(request):
    logout(request)
    return redirect(reverse_lazy('login'))


#vista principal de medicos
@permiso_medico#permiso de autorizacion para medicos
def doctors_index(request):
    context = {
        'mensaje': 'Gestión de medicos'
    }
    return render(request,'doctors/doctors_index.html', context)


#vista principal de pacientes
@permiso_medico
def patients_index(request):
    pacientes = Paciente.objects.all()
    context = {
        'pacientes': pacientes,
        'mensaje': 'Gestión de pacientes'
    }
    return render(request, 'patients/patients_index.html', context)

#vista principal citas
@login_required
def appointments_index(request):
    user = request.user
    
    # inicializa las variables medico y paciente en None
    medico = None
    paciente = None

    # verifica si el usuario es un médico y obtiene el objeto de médico
    if hasattr(user, 'medico'):
        medico = user.medico
    
    # verifica si el usuario es un paciente y obtiene el objeto de paciente
    if hasattr(user, 'paciente'):
        paciente = user.paciente

    context = {
        'user': user,
        'medico': medico,
        'paciente': paciente,
    }
    return render(request, 'base.html', context)


#vista principal de contacto
@login_required
def contact_index(request):
    context = {
        'mensaje': 'Gestión de contacto'
    }
    return render(request,'contact/contact_index.html', context)

#vista encargada de crear la cita medica
def CitaMedicaCreateView(request):
    #se verifica que el usuario esté autenticado y sea un paciente
    if not request.user.is_authenticated or not hasattr(request.user, 'paciente'):
        return render(request, 'no_login.html', {'message': 'No tienes permiso para crear citas.'})
    
    #obteniendo los dias disponibles para mostrarse en el template de la vista actual
    dias_disponibles = obtener_dias_disponibles()
    
    #validacion del formulario
    if request.method == 'POST':
        form = CitaMedicaForm(request.POST)
        if form.is_valid():
            #se verifica si ya existe una cita para la fecha seleccionada
            fecha = form.cleaned_data['fecha']
            medico = form.cleaned_data['medico']

            #se comprueba si existe una cita con la misma fecha y se muestra un error en caso de ser asi
            if CitaMedica.objects.filter(fecha=fecha, medico=medico).exists():
                
                return render(request, 'CRUD_appointments/error.html', {'form': form, 'error_message': 'No hay mas espacios para esa fecha'})

            #se crea una instancia de CitaMedica pendiente de guardar
            cita_medica = form.save(commit=False)

            #se asigna el paciente (usuario de la sesión) a la cita medica
            cita_medica.paciente = request.user.paciente

            #se guarda la cita médica con el paciente asignado
            cita_medica.save()

            #se redirecciona a la vista asiganda en caso se der almacenada correctamente
            return redirect(reverse_lazy('medical_appointments:appointments_list'))
    
    #caso contrario se renderiza el formulario de nuevo
    else:
        form = CitaMedicaForm()

    #se rederiza el template pasandole el diccionario
    return render(request, 'CRUD_appointments/citas_medicas_create.html', {'form': form, 'dias_disponibles':dias_disponibles})


#vista encargada de mostrar la lista de citas del paciente
@method_decorator(login_required, name='dispatch')
class CitaMedicaListView(ListView):
    #modelo a utilizar
    model = CitaMedica
    
    #template a utilizar
    template_name = 'CRUD_appointments/citas_medicas_list.html'
    
    #nombre de referencia para acceder a los objetos 
    context_object_name = 'solicitudes_citas'

    #se filtran las citas medicas del paciente actualmente autenticado
    def get_queryset(self):
        return CitaMedica.objects.filter(paciente=self.request.user.paciente)
    
    #metodo para pasarle al contexto los dias disponibles del metodo obtener_dias_disponibles()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dias_disponibles'] = obtener_dias_disponibles()        
        return context

#vista encargada de actualizar la cita por parte del paciente
@method_decorator(login_required, name='dispatch') 
class CitaMedicaUpdateView(UpdateView):
    #modelos a utilizar
    model = CitaMedica
    
    #formulario a utilizar
    form_class = CitaMedicaForm
    
    #template a renderizar
    template_name = 'CRUD_appointments/citas_medicas_create.html'
    
    #nombre de referencia para acceder a los objetos 
    context_object_name = 'cita'
    
    #vista a redireccionar despues de editar con exito
    success_url = reverse_lazy('citas_app:appointments_list')
    
    #metodo para pasarle al contexto los dias disponibles del metodo obtener_dias_disponibles()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        context['dias_disponibles'] = obtener_dias_disponibles()        
        return context
    

#vista encargada de eliminar una cita medica por parte del paciente
@method_decorator(login_required, name='dispatch') 
class CitaMedicaDeleteView(DeleteView):
    model = CitaMedica
    template_name = 'CRUD_appointments/citas_medicas_delete_confirm.html'
    context_object_name = 'cita'
    success_url = reverse_lazy('citas_app:appointments_list')
    
#metodo encargado de obtener las citas mas cercanas
def closest_appointments(request):
    #se obtiene la fecha y hora actual
    now = timezone.now()

    #se busca la cita medica mas cercana y confirmada
    proxima_cita = CitaMedica.objects.filter(
        paciente=request.user.paciente, #se filtra por el paciente actual
        fecha__gte=now,  #que la fecha sea mayor o igual a la actual
        confirmado=True, #que la cita este confirmada
        completada=False #que la cita aun no se encuentre completada
    ).order_by('fecha').first()#se ordenan las citas filtradas por fecha
    
    #se busca la cita medica mas cercana y solicitada

citas_app/templates/CRUD_appointments/citas_medicas_create.html
{% extends "CRUD_appointments/citas_medicas_list.html" %}

<!-- inicio_bloque_CRUD_citas -->
{% block bloque_CRUD_citas %}
    <h5 class="text-center">{% if cita %}Editar Cita Médica{% else %}Crear Cita Médica{% endif %}</h5>
    <div class="container card border rounded border-2 p-3">
        {% if cita %}
            <!-- Mensaje de edición -->
            <div class="alert alert-info text-center text-secondary">
                Esta es una cita existente. Puedes editarla aquí.
            </div>
        {% endif %}
        <form method="post" id="cita-form">
            {% csrf_token %}
            <table class="table table-striped border rounded border-3" >
                <tbody>

                    <!-- Fila 1: Campo Médico y Campo Fecha -->
                    <tr class="table-primary">
                        <td>
                            <div class="form-group">
                                <p class="p-2">{{ form.medico.label_tag }} {{ form.medico }}</p>
                                {% if form.medico.errors %}
                                    <p class="alert alert-danger mt-2">
                                        {{ form.medico.errors }}
                                    </p>
                                {% endif %}
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <p class="p-2">{{ form.fecha.label_tag }} <input type="date" id="id_fecha" name="fecha" class="form-control" required></p>
                            </div>
                        </td>
                    </tr>

                    <!-- Fila 2: Campo Hora y campo motivo -->
                    <tr class="table-secondary">
                        <td>
                            <div class="form-group">
                                <p class="p-2">{{ form.hora.label_tag }} {{ form.hora }}</p>
                                {% if form.hora.errors %}
                                    <p class="alert alert-danger mt-2">
                                        {{ form.hora.errors }}
                                    </p>
                                {% endif %}
                            </div>
                        </td>
                        <td colspan="2">
                            <div class="form-group">
                                <p class="p-2">{{ form.motivo.label_tag }} {{ form.motivo }}</p>
                                {% if form.motivo.errors %}
                                    <p class="alert alert-danger mt-2">
                                        {{ form.motivo.errors }}
                                    </p>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
            <button type="submit" class="btn btn-primary mt-3" id="botones_personalizados">
                {% if cita %}Guardar Cambios{% else %}Crear Cita{% endif %}
            </button>
        </form>
        {% if cita_exists %}
            <!-- Mensaje de error si ya existe una cita para la misma fecha -->
            <div class="alert alert-danger mt-3 text-secondary">
                Ya hay una cita para esta fecha. Revisa las fechas disponibles
            </div>
        {% endif %}
    </div>
{% endblock bloque_CRUD_citas %}
<!-- fin_bloque_CRUD_citas -->

citas_app/templates/CRUD_appointments/citas_medicas_delete_confirm.html
{% extends "CRUD_appointments/closest_appointments.html" %}

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}
<div class="container col-md-10 border rounded border-3 p-3">
    <h3 class="text-center bg-white p-3 border rounded border-2">Eliminar Cita Médica</h3>
    <hr>
    <p>¿Estás seguro de que deseas eliminar la siguiente cita médica?</p>

    <dl class="row">
		<dt class="col-sm-3">Codigo Cita:</dt>
		<dd class="col-sm-9">{{ cita.id }}</dd>

		<dt class="col-sm-3">Médico:</dt>
		<dd class="col-sm-9">{{ cita.medico }}</dd>

		<dt class="col-sm-3">Fecha:</dt>
		<dd class="col-sm-9">{{ cita.fecha }}</dd>

		<dt class="col-sm-3">Hora:</dt>
		<dd class="col-sm-9">{{ cita.hora }}</dd>

		<dt class="col-sm-3">Motivo:</dt>
		<dd class="col-sm-9">{{ cita.motivo }}</dd>
    </dl>

    <div class="">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="{% url 'medical_appointments:appointments_list' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</div>
{% endblock seccion_principal_02 %}
<!-- fin_seccion_principal_02 -->

citas_app/templates/CRUD_appointments/citas_medicas_list.html
{% extends "CRUD_appointments/closest_appointments.html" %}

<!-- inicio_bloque_CRUD_citas -->
{% block bloque_CRUD_citas %}
    <div class="container card border rounded border-2">
        <h5 class="text-center p-3">Listado de mis citas</h5>
        <div class="table-responsive border rounded border-2 p-1 m-1">
            <table class="table table-responsive bg-light">
                <thead>
                    <tr class="">
                        <th class="text-center" scope="col">Cod Cita</th>
                        <th class="text-center" scope="col">Médico</th>
                        <th class="text-center" scope="col">Fecha</th>
                        <th class="text-center" scope="col">Hora</th>
                        <th class="text-center" scope="col">Motivo</th>
                        <th class="text-center" scope="col">Estado</th> <!-- Agrega una columna para el estado -->
                        <th class="text-center" scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cita in solicitudes_citas %}
                        <tr class="">
                            <td class="text-center">{{ cita.id }}</td>
                            <td class="text-center">{{ cita.medico }}</td>
                            <td class="text-center">{{ cita.fecha }}</td>
                            <td class="text-center">{{ cita.hora }}</td>
                            <td class="text-center">{{ cita.motivo }}</td>
                            <td>
                                {% if cita.confirmado %}
                                    {% if cita.completada %}
                                        <span class="text-info">Finalizada</span>
                                    {% else %}
                                    <span class="text-success">Confirmada</span> 
                                    {% endif %}  
                                {% else %}
                                    <span class="text-warning">Pendiente</span>
                                {% endif %}
                            </td>
                            <td>
                                {% if cita.confirmado %}
                                    {% if cita.completada %}
                                        <a href="{% url 'citas_app:ver_historial_personal' cita.id %}" class="btn btn-sm btn-info">Detalles</a>                                        
                                    {% else %}
                                    <a href="{% url 'citas_app:ver_historial_personal' cita.id %}" class="btn btn-sm btn-success">Detalles</a>                                                                              
                                    {% endif %}
                                {% else %}  
                                <a href="{% url 'citas_app:appointments_update' cita.id %}" class="btn btn-primary btn-sm" title="Editar">
                                    <i class="fas fa-edit"></i> <!-- Ícono de edición -->
                                </a>
                                <a href="{% url 'citas_app:appointments_delete' cita.id %}" class="btn btn-danger btn-sm" title="Eliminar">
                                    <i class="fas fa-trash-alt"></i> <!-- Ícono de eliminación -->
                                </a> 
                                {% endif %}
                            </td>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock bloque_CRUD_citas %}
<!-- fin_bloque_CRUD_citas -->

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}
    <div class="container card border rounded border-2">
        <h3 class="mt-5 text-secondary text-center">Fechas cercanas disponibles</h3>
        <div class="row p-3">
            <div class="col-md-4 card border rounded border-3 p-3">
                <table class="table table-bordered table-primary">
                    <thead>
                        <tr>
                            <th class="text-mute text-center bg-info">Fechas</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for dia in dias_disponibles|slice:":7" %}
                            <tr>
                                <td class="text-center">{{ dia|date:"d-m-Y" }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td class="text-danger">No hay días disponibles este mes.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-4 offset-2 card border rounded border-3 p-3">
                <table class="table table-bordered table-primary">
                    <thead>
                        <tr>
                            <th class="text-mute text-center bg-info">Fechas</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for dia in dias_disponibles|slice:"7:" %}
                            <tr>
                                <td class="text-center">{{ dia|date:"d-m-Y" }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td class="text-danger">No hay días disponibles este mes.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock seccion_principal_02 %}
<!-- fin_seccion_principal_02 -->

citas_app/templates/CRUD_appointments/closest_appointments.html
{% extends "base.html" %}
{% load static %}

<!-- inicio_menu_sidebar -->
{% block menu_sidebar %}
    <nav class="navbar navbar-expand mt-2 mb-2" style="background-color: #eceef0;" id="botones_personalizados">
        <div class="container">            
            <a class="navbar-brand" href="{% url 'medical_appointments:closest_appointments' %}">
                <i class="fas fa-home"></i> Inicio
            </a>         
            <ul class="navbar-nav justify-content-center nav-fill">                
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'citas_app:appointments_list' %}">Mis Citas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-link" href="{% url 'citas_app:appointments_create' %}">Solicitar una cita</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-link" href="{% url 'citas_app:historial_completo_paciente' %}">Mi Historial</a>
                </li>
                
            </ul>
        </div>
    </nav>                
{% endblock menu_sidebar %}
<!-- fin_menu_sidebar -->

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}
    <h3 class="text-center card p-3 text-dark col-md-8 offset-1 " id="botones_personalizados" style="border-radius: 15px;">Mis notificaciones</h3>
    {% if proxima_cita %}
        <div class="card border rounded border-2 col-md-8 offset-1 p-2 bg-success mb-1">
            <div class="card-body">
                <h4 class="card-title">Cita confirmadas</h4>
                <p class="card-text">La próxima cita es el {{ proxima_cita.fecha|date:"l, d F Y" }} a las {{ proxima_cita.hora|time:"H:i" }}.
                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Motivo: {{ proxima_cita.motivo }}</p></li>
                <li class="list-group-item">Tu cita fué confirmada por el médico: {{ proxima_cita.medico.nombre_medico }} {{ proxima_cita.medico.apellido_medico }}</li>
            </ul>
        </div>
    {% else %}
        <h3 class="text-center p-3">Aun no tienes citas confirmadas</h3>
    {% endif %}
    {% if proxima_cita_solicitada %}    
        <div class="card border rounded border-2 col-md-8 offset-1 p-2 bg-info mb-1">
            <div class="card-body">
                <h4 class="card-title">Cita solicita mas cercana</h4>
                <p class="card-text">Fecha: {{ proxima_cita_solicitada.fecha|date:"l, d F Y" }} a las {{ proxima_cita_solicitada.hora|time:"H:i" }}.
                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Motivo: {{ proxima_cita_solicitada.motivo }}</p></li>
                <li class="list-group-item">Tu cita fué agendada con el médico: {{ proxima_cita_solicitada.medico.nombre_medico }} {{ proxima_cita_solicitada.medico.apellido_medico }} a espera de confimación</li>
            </ul>
        </div>
    {% else %}
        <div class="container offset-1 p-3 mt-3">
            <h3 class="text-secondary">No tienes citas pendientes de confirmación</h3>
        </div>
    {% endif %}
{% endblock seccion_principal_02 %}
<!-- fin_seccion_principal_02 -->

citas_app/templates/CRUD_appointments/error.html
{% extends "base.html" %}

<!-- inicio_bloque_CRUD_citas -->
{% block bloque_CRUD_citas %}
    <h5 class="text-center">{% if cita %}Editar Cita Médica{% else %}Crear Cita Médica{% endif %}</h5>
    <div class="container">
        {% if error_message %}
            <div class="alert alert-danger">
                {{ error_message }}
            </div>
        {% endif %}
        <a class="btn btn-sm btn-primary" href="{% url 'citas_app:appointments_create' %}">Crear una cita</a>
    </div>
{% endblock bloque_CRUD_citas %}
<!-- fin_bloque_CRUD_citas -->