citas_app/urls.py
from django.urls import path
from . import views
from .views import *

#namespace para acceder a las urls de la aplicacion 'citas_app'
app_name = 'citas_app'

urlpatterns = [
    path('user_registration/', UserRegisterView.as_view(), name='user_registration_view'), 
    path('full_user_registration/', CompletePatientRecordView.as_view(), name='full_patient_registration_view'), 
    path('appointments_index/', appointments_index, name='appointments_index'),    
    path('patients_index/',patients_index, name='patients_index'),
    path('contact_index/',contact_index, name='contact_index'), 
    path('appointments_list/', CitaMedicaListView.as_view(), name='appointments_list'),
    path('closest_appointments/', closest_appointments, name='closest_appointments'),
    path('appointments_create/', CitaMedicaCreateView, name='appointments_create'),
    path('appointments_update/<int:pk>/', CitaMedicaUpdateView.as_view(), name='appointments_update'),
    path('appointments_delete/<int:pk>/', CitaMedicaDeleteView.as_view(), name='appointments_delete'),  
    path('doctors_index/',doctors_index, name='doctors_index'),
    path('doctors_list/', MedicoListView, name='doctors_list'),
    path('doctors_create/', views.MedicoCreateView, name='doctors_create'),
    path('vista_solicitudes_medico/', vista_solicitudes_medico, name='vista_solicitudes_medico'),
    path('doctors_update/<int:pk>/', MedicoUpdateView, name='doctors_update'),
    path('doctors_delete/<int:pk>/', MedicoDeleteView, name='doctors_delete'),
    path('appointments_index_profile_edit/', EditarPerfilPacienteView.as_view(), name='appointments_index_profile_edit'),  
    path('citas_confirmadas_calendar/', CitasConfirmadasCalendar.as_view(), name='citas_confirmadas_calendar'),
    path('confirmar_cita_medico/<int:cita_id>/', confirmar_cita_medico, name='confirmar_cita_medico'),
    path('obtener_eventos/', obtener_eventos, name='obtener_eventos'),
    path('completar_cita/<int:cita_id>/', views.completar_cita, name='completar_cita'),
    path('ver_historial/<int:cita_id>/', ver_historial, name='ver_historial'),
    path('ver_historial_completo/<int:paciente_id>/',ver_historial_completo, name='ver_historial_completo'),
    path('reprogramar-cita/<int:cita_id>/', views.reprogramar_cita, name='reprogramar_cita'),
    path('historial_completo_paciente/', historial_completo_paciente, name='historial_completo_paciente'),
    path('specialties_index/', EspecialidadesView, name='specialties_index'),
    path('citas_generales/', citas_generales, name='citas_generales'),
    path('ver_historial_personal/<int:cita_id>/', ver_historial_personal, name='ver_historial_personal'),
    ]

citas_medicas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from citas_app import views

app_name = 'citas_app' 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.custom_logout_view, name='logout'),
    path('no_login_view/', views.no_login_view, name='no_login_view'), 
    path('medical_appointments/', include('citas_app.urls', namespace='medical_appointments')),
]

      

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Login - MedApp</title>
{% endblock title %}

{% block contenido_global %}
<div class="container mt-5 mb-3">
    <div class="container-fluid">
        <div class="container col-xs-6 col-sm-12 col-md-7 col-lg-4 mt-4 mb-4 card">
            <img src="{% static 'img/logo_medapp.png' %}" alt="user_name_img_avatar" class="img-fluid mt-2 p-2" style="border-radius: 10px;">

            {% block formulario_login_registro %}
            <div class="container col-sm-12 col-md-6 col-lg-8 container-transition">
                <h3 class="mt-3 text-secondary">Inicio de sesión</h3>
                <form method="post">
                    {% csrf_token %}
                    
                    <div class="form-group mt-3">
                        <label for="{{ form.username.id_for_label }}">Nombre de usuario:</label>
                        <input type="text" name="{{ form.username.name }}" class="form-control" id="{{ form.username.id_for_label }}" placeholder="Ingresa tu usuario" autofocus>
                        
                        <!-- Mensajes de error para el campo de nombre de usuario -->
                        {% if form.username.errors %}
                            {% for error in form.username.errors %}
                                <div class="alert alert-danger mt-2">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                
                    <div class="form-group mt-3">
                        <label for="{{ form.password.id_for_label }}">Contraseña de usuario:</label>
                        <input type="password" name="{{ form.password.name }}" class="form-control" id="{{ form.password.id_for_label }}" placeholder="Ingresa tu contraseña">
                        
                        <!-- Mensajes de error para el campo de contraseña -->
                        {% if form.password.errors %}
                            {% for error in form.password.errors %}
                                <div class="alert alert-danger mt-2">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    
                    <button type="submit" class="btn btn-sm mt-3" id="botones_personalizados">Iniciar sesión</button>
                    
                    <div class="">
                        <p class="mt-2 text-dark">
                            ¿No tienes una cuenta? 
                        </p>      
                        <a name="botones_personalizados" id="botones_personalizados" class="btn btn-sm mb-3" href="{% url 'citas_app:user_registration_view' %}" role="button">Regístrate aquí</a>
                    </div>  
                </form>                                                          
            </div>
            {% endblock formulario_login_registro %}
            
        </div>
    </div>
</div>
{% endblock contenido_global %}

templates/no_login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Login - MedApp</title>
{% endblock title %}

<!-- inicio_contenido_global -->
{% block contenido_global %}
<div class="container mt-5 mb-3">
    <div class="container-fluid">
        <div class="container col-xs-6 col-sm-12 col-md-7 col-lg-4 mt-4 mb-4 card">
            <img src="{% static 'img/logo_medapp.png' %}" alt="user_name_img_avatar" class="img-fluid mt-2 p-2" style="border-radius: 10px;">
            <div id="myAlert" class="alert alert-light alert-dismissible fade show text-center" role="alert">
                <p class="lead">Ups! algo salió mal :( {{mensaje}}</p>
                <!-- Agrega enlaces a las vistas de inicio de sesión y registro -->
                <a name="botones_personalizados" id="botones_personalizados" class="btn btn-sm mb-3" href="{% url 'citas_app:appointments_index' %}" role="button">Intenta de nuevo...</a>
            </div>
        </div>
    </div>
</div>
{% endblock contenido_global %}
<!-- fin_contenido_global -->