citas_app/urls.py
from django.urls import path
from . import views
from .views import *

#namespace para acceder a las urls de la aplicacion 'citas_app'
app_name = 'citas_app'

urlpatterns = [
    path('user_registration/', UserRegisterView.as_view(), name='user_registration_view'), 
    path('full_user_registration/', CompletePatientRecordView.as_view(), name='full_patient_registration_view'), 
    path('appointments_index/', appointments_index, name='appointments_index'),    
    path('patients_index/',patients_index, name='patients_index'),
    path('contact_index/',contact_index, name='contact_index'), 
    path('appointments_list/', CitaMedicaListView.as_view(), name='appointments_list'),
    path('closest_appointments/', closest_appointments, name='closest_appointments'),
    path('appointments_create/', CitaMedicaCreateView, name='appointments_create'),
    path('appointments_update/<int:pk>/', CitaMedicaUpdateView.as_view(), name='appointments_update'),
    path('appointments_delete/<int:pk>/', CitaMedicaDeleteView.as_view(), name='appointments_delete'),  
    path('doctors_index/',doctors_index, name='doctors_index'),
    path('doctors_list/', MedicoListView, name='doctors_list'),
    path('doctors_create/', views.MedicoCreateView, name='doctors_create'),
    path('vista_solicitudes_medico/', vista_solicitudes_medico, name='vista_solicitudes_medico'),
    path('doctors_update/<int:pk>/', MedicoUpdateView, name='doctors_update'),
    path('doctors_delete/<int:pk>/', MedicoDeleteView, name='doctors_delete'),
    path('appointments_index_profile_edit/', EditarPerfilPacienteView.as_view(), name='appointments_index_profile_edit'),  
    path('citas_confirmadas_calendar/', CitasConfirmadasCalendar.as_view(), name='citas_confirmadas_calendar'),
    path('confirmar_cita_medico/<int:cita_id>/', confirmar_cita_medico, name='confirmar_cita_medico'),
    path('obtener_eventos/', obtener_eventos, name='obtener_eventos'),
    path('completar_cita/<int:cita_id>/', views.completar_cita, name='completar_cita'),
    path('ver_historial/<int:cita_id>/', ver_historial, name='ver_historial'),
    path('ver_historial_completo/<int:paciente_id>/',ver_historial_completo, name='ver_historial_completo'),
    path('reprogramar-cita/<int:cita_id>/', views.reprogramar_cita, name='reprogramar_cita'),
    path('historial_completo_paciente/', historial_completo_paciente, name='historial_completo_paciente'),
    path('specialties_index/', EspecialidadesView, name='specialties_index'),
    path('citas_generales/', citas_generales, name='citas_generales'),
    path('ver_historial_personal/<int:cita_id>/', ver_historial_personal, name='ver_historial_personal'),
    ]

citas_medicas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView
from citas_app import views

app_name = 'citas_app' 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.custom_logout_view, name='logout'),
    path('no_login_view/', views.no_login_view, name='no_login_view'), 
    path('medical_appointments/', include('citas_app.urls', namespace='medical_appointments')),
]

      

citas_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Paciente(models.Model):
    
    """
    Modelo de paciente.
    Atributos:
    - usuario_paciente: Usuario para que el paciente agente su cita
    - nombre_paciente: Nombre del paciente.
    - apellido_paciente: Apellido del paciente.
    - edad_paciente: Edad del paciente.
    - sexo_paciente: Sexo del paciente.
    - fecha_nac_paciente: Fecha de nacimiento del paciente.
    """
    
    usuario_paciente = models.OneToOneField(User, on_delete=models.CASCADE, default=None )
    nombre_paciente = models.CharField(max_length=100, null=True)
    apellido_paciente = models.CharField(max_length=100)
    edad_paciente = models.PositiveIntegerField(default=0)
    sexo_paciente = models.CharField(max_length=10, null=True)
    fecha_nac_paciente = models.DateField(default=None)
    
    def __str__(self):
        return f"{self.nombre_paciente} {self.apellido_paciente}"
    
class Medico(models.Model):
    """
    Modelo de médico.
    Atributos:
    - nombre_medico: Nombre del médico.
    - apellido_medico: Apellido del médico.
    - especialidad_medico: Especialidad del médico.
    - usuario_medico: Usuario del médico para poder consultar las citas.
        
    """
    nombre_medico = models.CharField(max_length=100)
    apellido_medico = models.CharField(max_length=100)
    especialidad_medico = models.CharField(max_length=100)
    usuario_medico = models.OneToOneField(User, on_delete=models.CASCADE, related_name='medico')
        
    def __str__(self):
        return f"{self.nombre_medico}{self.apellido_medico}"
    
    
class CitaMedica(models.Model):
    """
    Modelo de cita médica.
    Atributos:
    - paciente: Paciente que tiene la cita.
    - medico: Médico que atiende la cita.
    - fecha: Fecha de la cita.
    - hora: Hora de la cita.
    - motivo: Motivo de la cita.
"""
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE)
    fecha = models.DateField(default='2023-01-01')
    hora = models.TimeField(default='00:00')
    motivo = models.CharField(max_length=200)
    confirmado = models.BooleanField(default=False)
    completada = models.BooleanField(default=False)   
    def __str__(self):
        return f'Cita Médica #{self.id} - Paciente: {self.paciente.nombre_paciente}, Médico: {self.medico.nombre_medico}'



class CompletarHistorial(models.Model):
    """
    Modelo que representa el historial médico completo de una cita médica.
    Atributos:
    - cita_medica: La cita médica a la que se relaciona este historial.
    - paciente: El paciente relacionado con este historial.
    - fecha: La fecha de creación del historial (se autocompleta).
    - diagnostico: El diagnóstico del paciente para la cita médica.
    - tratamiento: El tratamiento recomendado para el paciente.
    """
    cita_medica = models.ForeignKey(CitaMedica, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now=True)
    diagnostico = models.TextField()
    tratamiento = models.TextField()
    
    def __str__(self):
        return f"{self.cita_medica}"

citas_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy,reverse
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Paciente, Medico, CitaMedica, CompletarHistorial
from .forms import CitaMedicaForm, PacienteForm, MedicoForm, CitaMedicaForm, CustomUserCreationForm, CompletarHistorialForm, ReprogramarCitaForm
from schedule.models import Calendar, Event
from datetime import datetime, timedelta
from .decorators import permiso_medico

#vista encargada del registro inicial de usuario
class UserRegisterView(CreateView):        
    #template a renderizar 
    template_name = 'user_patient_register/user_register.html'
    
    #formulario base
    form_class = UserCreationForm
    
    #metodo de validacion de formulario e inicio de sesion
    def form_valid(self, form):        
        #respuesta al estar validado el formulario
        response = super().form_valid(form)
        
        #encriptando contraseña de usuario para almacenarla en la base de datos
        self.object.set_password(form.cleaned_data['password1'])
        
        #guardando objeto
        self.object.save()
        
        #iniciando sesion de forma automatica
        login(self.request, self.object)
        
        #devolviendo la respuesta
        return response
    
    #metodo para redireccionar la vista al ser validado el formulario
    def get_success_url(self):
        return reverse_lazy('citas_app:full_patient_registration_view')
    
    
#vista encargada de continuar el registro completo del paciente
@method_decorator(login_required, name='dispatch')
class CompletePatientRecordView(CreateView):    
    #template a renderizar
    template_name = 'user_patient_register/full_patient_registration.html'    
    
    #modelo base para renderizar el formulario
    model = Paciente    
    
    #campos a mostrar en el template
    fields = [
        'nombre_paciente',
        'apellido_paciente',
        'edad_paciente',
        'sexo_paciente',
        'fecha_nac_paciente',
    ]    
    
    #redireccion despues de validar el formulario
    success_url = reverse_lazy('citas_app:appointments_index')
    
    #metodo para validar el formulario y enviar informacion
    def form_valid(self, form):        
        #asociando el usuario de la sesion actual al campo usuario_paciente del formulario
        form.instance.usuario_paciente = self.request.user        
        
        #enviando informacion 
        return super().form_valid(form)

    
#vista encargada de editar el perfil del paciente
class EditarPerfilPacienteView(UpdateView):
    #modelo a utilizar
    model = Paciente
    
    #formualario a utilizar
    form_class = PacienteForm
    
    #template a renderizar
    template_name = 'user_patient_register/full_patient_registration_edit.html'
    
    #vista a redireccionar despues de editar con exito
    success_url = reverse_lazy('citas_app:appointments_index')

    #recuperando el perfil del paciente actual
    def get_object(self):
        return Paciente.objects.get(usuario_paciente=self.request.user)
    
#vista encargada de usuario no autenticado    
def no_login_view(request):
    
    context = {
        'mensaje': 'Gracias por visitarnos, inicia sesion para gestionar tus citas'
    }
    return render(request,'no_login.html', context)


#vista encargada de cerrar sesion de usuario
def custom_logout_view(request):
    logout(request)
    return redirect(reverse_lazy('login'))


#vista principal de medicos
@permiso_medico#permiso de autorizacion para medicos
def doctors_index(request):
    context = {
        'mensaje': 'Gestión de medicos'
    }
    return render(request,'doctors/doctors_index.html', context)


#vista principal de pacientes
@permiso_medico
def patients_index(request):
    pacientes = Paciente.objects.all()
    context = {
        'pacientes': pacientes,
        'mensaje': 'Gestión de pacientes'
    }
    return render(request, 'patients/patients_index.html', context)

#vista principal citas
@login_required
def appointments_index(request):
    user = request.user
    
    # inicializa las variables medico y paciente en None
    medico = None
    paciente = None

    # verifica si el usuario es un médico y obtiene el objeto de médico
    if hasattr(user, 'medico'):
        medico = user.medico
    
    # verifica si el usuario es un paciente y obtiene el objeto de paciente
    if hasattr(user, 'paciente'):
        paciente = user.paciente

    context = {
        'user': user,
        'medico': medico,
        'paciente': paciente,
    }
    return render(request, 'base.html', context)


#vista principal de contacto
@login_required
def contact_index(request):
    context = {
        'mensaje': 'Gestión de contacto'
    }
    return render(request,'contact/contact_index.html', context)

#vista encargada de crear la cita medica
def CitaMedicaCreateView(request):
    #se verifica que el usuario esté autenticado y sea un paciente
    if not request.user.is_authenticated or not hasattr(request.user, 'paciente'):
        return render(request, 'no_login.html', {'message': 'No tienes permiso para crear citas.'})
    
    #obteniendo los dias disponibles para mostrarse en el template de la vista actual
    dias_disponibles = obtener_dias_disponibles()
    
    #validacion del formulario
    if request.method == 'POST':
        form = CitaMedicaForm(request.POST)
        if form.is_valid():
            #se verifica si ya existe una cita para la fecha seleccionada
            fecha = form.cleaned_data['fecha']
            medico = form.cleaned_data['medico']

            #se comprueba si existe una cita con la misma fecha y se muestra un error en caso de ser asi
            if CitaMedica.objects.filter(fecha=fecha, medico=medico).exists():
                
                return render(request, 'CRUD_appointments/error.html', {'form': form, 'error_message': 'No hay mas espacios para esa fecha'})

            #se crea una instancia de CitaMedica pendiente de guardar
            cita_medica = form.save(commit=False)

            #se asigna el paciente (usuario de la sesión) a la cita medica
            cita_medica.paciente = request.user.paciente

            #se guarda la cita médica con el paciente asignado
            cita_medica.save()

            #se redirecciona a la vista asiganda en caso se der almacenada correctamente
            return redirect(reverse_lazy('medical_appointments:appointments_list'))
    
    #caso contrario se renderiza el formulario de nuevo
    else:
        form = CitaMedicaForm()

    #se rederiza el template pasandole el diccionario
    return render(request, 'CRUD_appointments/citas_medicas_create.html', {'form': form, 'dias_disponibles':dias_disponibles})


#vista encargada de mostrar la lista de citas del paciente
@method_decorator(login_required, name='dispatch')
class CitaMedicaListView(ListView):
    #modelo a utilizar
    model = CitaMedica
    
    #template a utilizar
    template_name = 'CRUD_appointments/citas_medicas_list.html'
    
    #nombre de referencia para acceder a los objetos 
    context_object_name = 'solicitudes_citas'

    #se filtran las citas medicas del paciente actualmente autenticado
    def get_queryset(self):
        return CitaMedica.objects.filter(paciente=self.request.user.paciente)
    
    #metodo para pasarle al contexto los dias disponibles del metodo obtener_dias_disponibles()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dias_disponibles'] = obtener_dias_disponibles()        
        return context

#vista encargada de actualizar la cita por parte del paciente
@method_decorator(login_required, name='dispatch') 
class CitaMedicaUpdateView(UpdateView):
    #modelos a utilizar
    model = CitaMedica
    
    #formulario a utilizar
    form_class = CitaMedicaForm
    
    #template a renderizar
    template_name = 'CRUD_appointments/citas_medicas_create.html'
    
    #nombre de referencia para acceder a los objetos 
    context_object_name = 'cita'
    
    #vista a redireccionar despues de editar con exito
    success_url = reverse_lazy('citas_app:appointments_list')
    
    #metodo para pasarle al contexto los dias disponibles del metodo obtener_dias_disponibles()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        context['dias_disponibles'] = obtener_dias_disponibles()        
        return context
    

#vista encargada de eliminar una cita medica por parte del paciente
@method_decorator(login_required, name='dispatch') 
class CitaMedicaDeleteView(DeleteView):
    model = CitaMedica
    template_name = 'CRUD_appointments/citas_medicas_delete_confirm.html'
    context_object_name = 'cita'
    success_url = reverse_lazy('citas_app:appointments_list')
    
#metodo encargado de obtener las citas mas cercanas
def closest_appointments(request):
    #se obtiene la fecha y hora actual
    now = timezone.now()

    #se busca la cita medica mas cercana y confirmada
    proxima_cita = CitaMedica.objects.filter(
        paciente=request.user.paciente, #se filtra por el paciente actual
        fecha__gte=now,  #que la fecha sea mayor o igual a la actual
        confirmado=True, #que la cita este confirmada
        completada=False #que la cita aun no se encuentre completada
    ).order_by('fecha').first()#se ordenan las citas filtradas por fecha
    
    #se busca la cita medica mas cercana y solicitada

citas_app/templates/doctors/doctors_delete.html
{% extends 'doctors/doctors_list.html' %}
{% load static %}

<!-- inicio_titulo -->
{% block title %}
    <title>Médicos - MedApp</title>
{% endblock title %}
<!-- fin_titulo -->

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}
<div class="container col-md-8 mt-4 card p-5 border rounded border-3">
    <h1>Eliminar Médico</h1>
    <p>¿Estás seguro de que deseas eliminar este médico?</p>

    <dl class="row">
        <dt class="col-sm-3">ID:</dt>
        <dd class="col-sm-9">{{ medico.id }}</dd>
        
        <dt class="col-sm-3">Usuario:</dt>
        <dd class="col-sm-9">{{ medico.usuario_medico }}</dd>

        <dt class="col-sm-3">Nombre:</dt>
        <dd class="col-sm-9">{{ medico.nombre_medico }}</dd>

        <dt class="col-sm-3">Apellido:</dt>
        <dd class="col-sm-9">{{ medico.apellido_medico }}</dd>

        <dt class="col-sm-3">Especialidad:</dt>
        <dd class="col-sm-9">{{ medico.especialidad_medico }}</dd>
    </dl>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'medical_appointments:doctors_list' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock seccion_principal_02 %}
<!-- fin_seccion_principal_02 -->

citas_app/templates/doctors/doctors_index.html
{% extends "base.html" %}

citas_app/templates/doctors/doctors_list.html
{% extends "doctors/doctors_index.html" %}

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}
    <div class="container mt-3">
        <h5 class="text-center">Lista de Medicos</h5>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">Usuario</th>
                        <th class="text-center" scope="col">Nombre</th>
                        <th class="text-center" scope="col">Apellido</th>
                        <th class="text-center" scope="col">Especialidad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for medico in medicos %}
                        <tr>
                            <td class="text-center">{{ medico.usuario_medico }}</td>
                            <td class="text-center">{{ medico.nombre_medico }}</td>
                            <td class="text-center">{{ medico.apellido_medico }}</td>
                            <td class="text-center">{{ medico.especialidad_medico }}</td>
                            <td class="text-center">
                                <a href="{% url 'citas_app:doctors_update' medico.id %}" class="btn btn-primary btn-sm" title="Editar">
                                    <i class="fas fa-edit"></i> <!-- Ícono de edición -->
                                </a>
                                <a href="{% url 'citas_app:doctors_delete' medico.id %}" class="btn btn-danger btn-sm" title="Eliminar">
                                    <i class="fas fa-trash-alt"></i> <!-- Ícono de eliminación -->
                                </a>
                            </td>
                            
                            

                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>                                
{% endblock seccion_principal_02 %}
<!-- fin_seccion_principal_02 -->

citas_app/templates/doctors/especialidades.html
{% extends "base.html" %}
{% load static %}

<!-- inicio_bloque_CRUD_citas -->
{% block bloque_CRUD_citas %}
    <div class="container">
        <h3 class="text-center text-secondary p-3 m-3">Médicos y Especialidades</h3>
        <input type="text" id="searchInput" class="form-control" placeholder="Buscar por medico o especialidad">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-secondary">Nombre   |   Especialidad</th>
                </tr>
            </thead>
            <tbody>
                {% for medico in medicos %}
                    <tr>
                        <td>{{ medico.nombre_medico }} {{ medico.apellido_medico }} | {{ medico.especialidad_medico }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>    
{% endblock bloque_CRUD_citas %}
<!-- fin_bloque_CRUD_citas -->

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}    
    
    <!-- inicio_contenedor_info_carousel -->
    <div id="carouselId01" class="carousel slide p-3" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/medico01.png' %}" alt="Médico 1" class="d-block" height="300" style="border-radius: 10px;">
                <div class="carousel-caption card col-md-6 offset-3" style="border-radius: 10px;">
                    <h3 class="text-secondary">Dr. Domínguez</h3>
                    <h2 class="text-secondary">Dentista</h2>
                    <div class="container col-6">
                        <p class="text-secondary">Dentista con mas de 4 años de ejercer en nuestro consultorio</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/medico02.png' %}" alt="Médico 2" class="d-block" height="300" style="border-radius: 10px;">
                <div class="carousel-caption card col-md-6 offset-3" style="border-radius: 10px;">
                    <h3 class="text-secondary">Dra. Castro</h3>
                    <h2 class="text-secondary">Oftalmologo</h2>
                    <div class="container col-6">
                        <p class="text-secondary">Medico Oftalmologo especialista con mas de 7 años de ejercer en nuestro consultorio</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/medico03.png' %}" alt="Médico 3" class="d-block" height="300" style="border-radius: 10px;">
                <div class="carousel-caption  card col-md-6 offset-3" style="border-radius: 10px;">
                    <h3 class="text-secondary">Dra. Sanchez</h3>
                    <h2 class="text-secondary">Pediatra</h2>
                    <div class="container col-6">
                        <p class="text-secondary">Pediatría especialista con mas de 6 años de ejercer en nuestro consultorio</p>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselId01" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="false"></span>
            <span class="text-dark">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselId01" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="false"></span>
            <span class="text-dark">Siguiente</span>
        </button>
    </div>
    
    <!-- inicio_contenedor_info_consultorio -->
    <div class="card container p-3 m-3 bg-light col-11">
        <div class="card-body">
            <h5 class="card-title text-center text-secondary">Nuestros Profesionales de la Salud</h5>
            <p class="card-text text-secondary">En nuestro consultorio médico, nos enorgullece contar con un equipo de médicos altamente calificados y comprometidos con su salud y bienestar. Todos nuestros médicos cuentan con licencia para ejercer la medicina y están dedicados a brindar atención médica de calidad a nuestros pacientes.</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item text-muted">Equipo de médicos especializados</li>
            <li class="list-group-item text-muted">Atención médica integral</li>
            <li class="list-group-item text-muted">Compromiso con la salud de nuestros pacientes</li>
        </ul>
        {% if user.paciente %}
            <div class="card-body">
                <a href="{% url 'citas_app:appointments_create' %}" class="card-link btn btn-sm btn-primary">Solicita una cita</a>
            </div>
        {% else %}
        {% endif %}

    </div>

{% endblock seccion_principal_02 %} 
<!-- fin_seccion_principal_02 -->

<!-- inicio_notificaciones -->
{% block notificaciones %}
  
{% endblock notificaciones %}
<!-- fin_notificaciones -->

citas_app/templates/doctors/reprogramar_cita.html
{% extends "doctors/vista_solicitudes_medico.html" %}

<!-- inicio_bloque_CRUD_citas -->
{% block bloque_CRUD_citas %}
    <div class="container border rounded border-2 p-3">
    <form method="post" id="cita-form">
        {% csrf_token %}
        {% if cita %}
            <!-- Mensaje de edición -->
            <div class="row alert alert-info text-center">
            <h5>Editando cita medica cod: {{cita.id}}</h5>
            </div>
        {% endif %} 

        <table class="table table-striped table-inverse table-responsive p-3">
            <div class="form-group">
                <p class="p-2">{{ form.fecha.p_tag }}<input type="date" id="id_fecha" name="fecha" class="form-control" required></p>
            </div>
            <thead class="thead-inverse">
                <tr class="p-1">
                    <th class="table-primary p-1 text-primary">{{ form.hora.label_tag }}</th>
                    <th class="table-primary p-1 text-primary">{{ form.motivo.label_tag }}</th>
                    <th class="table-primary p-1 text-primary">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ form.hora }}</td> 
                        {% if form.hora.errors %}
                            <p class="alert alert-danger mt-2">
                                {{ form.hora.errors }}
                            </p>
                        {% endif %}
                    <td>{{ form.motivo }}</td> 
                        {% if form.motivo.errors %}
                            <p class="alert alert-danger mt-2">
                            {{ form.motivo.errors }}
                        </p>
                    {% endif %}
                    <td colspan="2">
                        <button type="submit" class="btn btn-sm" id="botones_personalizados">
                            {% if cita %}Guardar Cambios{% else %}Crear Cita{% endif %}
                        </button>
                    </td>
                </tr>
            </tbody>
            <!-- Mensaje de error si ya existe una cita para la misma fecha -->
            {% if cita_exists %}
            <div class="alert alert-danger mt-3">
            Ya tienes una cita para esta fecha. No puedes crear otra.
            </div>
            {% endif %}
        </table>
    </form>
{% endblock bloque_CRUD_citas %}
<!-- fin_bloque_CRUD_citas -->

citas_app/templates/doctors/vista_solicitudes_medico.html
{% extends "base.html" %}

<!-- inicio_bloque_CRUD_medicos -->
{% block bloque_CRUD_citas %}
    <div class="table-responsive">
        <input type="text" id="searchInput" class="form-control" placeholder="Buscar">
        <table class="table table-bordered mt-2">
            <thead>
                <tr class="table-primary">
                    <th class="text-center">Cod Cita</th>
                    <th class="text-center">Paciente</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Hora</th>
                    <th class="text-center">Motivo</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for cita in solicitudes_citas %}
                    <tr class="table-secondary">
                        <td>{{ cita.id }}</td>
                        <td>{{ cita.paciente }}</td>
                        <td>{{ cita.fecha }}</td>
                        <td>{{ cita.hora }}</td>
                        <td>{{ cita.motivo }}</td>
                        <td>
                            {% if cita.confirmado %}
                                {% if cita.completada %}
                                    <span class="text-info">Finalizada</span>
                                {% else %}
                                    <span class="text-success">Confirmada</span>
                                {% endif %}
                            {% else %}
                                <span class="text-warning">Pendiente de confirmar</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if cita.confirmado %}
                                {% if cita.completada %}
                                    <a href="{% url 'citas_app:ver_historial' cita.id %}" class="btn btn-sm btn-info">Ver detalles</a>
                                {% else %}
                                    <a href="{% url 'citas_app:completar_cita' cita.id %}" class="btn btn-sm btn-success">Iniciar</a>
                                {% endif %}
                            {% else %}
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-xl-5 col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                            <a href="{% url 'citas_app:confirmar_cita_medico' cita.id %}" class="btn btn-sm btn-warning">Confirmar</a>
                                        </div>
                                        <div class="col-xl-5 col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                            <a href="{% url 'citas_app:reprogramar_cita' cita.id %}" class="btn btn-sm btn-danger">Reprogramar</a>
                                        </div>
                                    </div>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock bloque_CRUD_citas %}
<!-- fin_bloque_CRUD_citas -->

<!-- inicio_seccion_principal_02 -->
{% block seccion_principal_02 %}
    {% include "doctors/calendario_citas_confirmadas.html" %}
{% endblock seccion_principal_02 %}
<!-- fin_seccion_principal_02 -->